### ISSUE TITLE
[PE-D][Tester C] If a special character is added to ID in addressbook.json, view command for that contact does not work

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-F10-2/tp#147]
Steps to reproduce with an empty address book:
- add -name Xiao Ming -address 13, Computing Dr, 117417 -email xiaoming@email.com -phone 88888888 -subject Math 
- close application
- open data/addressbook.json 
- change uniqueId from 000001 to *000001
- open application
- input view -id *000001

It shows invalid command format however *000001 is an ID for the contact

![Screenshot 2024-04-05 at 4.44.38 PM.png](https://raw.githubusercontent.com/martinng01/ped/main/files/2ac4866c-6485-44fa-9ebc-76cec279e90a.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: martinng01/ped#5

**Comment by MarcusGitty** [comment]
This is part of application security, not fixing it

**Comment by MarcusGitty** [comment]
Realised that this is a bug and the expected outcome should be addresbook deems the data to be invalid and reloads with blank page as per original AB3 UG under editing the data file


![image](https://github.com/AY2324S2-CS2103T-F10-2/tp/assets/122339963/ad91af10-011c-4443-8530-16b5a846a9dd)

**Comment by MarcusGitty** [comment]
Fixed by #207

**Comment by MarcusGitty** [comment]
https://github.com/nus-cs2103-AY2324S2/forum/issues/811#issuecomment-2053553793

Meets current level as  'if you edit the file correctly, things will work. But if you edited it wrongly, there's no guarantee that things will work'. So, I assume you already meet this bar?"

so not allowed to fix
