### ISSUE TITLE
[PE-D][Tester A] delete example is unclear

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-F10-2/tp#148]
![image.png](https://raw.githubusercontent.com/Tanzhiheng26/ped/main/files/4493c362-cb92-43d0-82e3-360a228e2c69.png)

At first I thought that `delete -id 000001 / 1` was the actual command to execute. It would be clearer if the example was something like: `delete -id 000001` or `delete -id 1` deletes the student with the id 000001.

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: Tanzhiheng26/ped#5

**Comment by MarcusGitty** [comment]
Fixed by PR #203 , thanks @KinTatHo
