### ISSUE TITLE
[PE-D][Tester D] Id number of student cannot be seen if their names are too long

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-F10-2/tp#149]
1. Add a new student with a very long name e.g. Ong Xiao Ming Ling Ling Christopher Prince Alexander GreenSwift Leonardo The Third

Expected: 
Should be able to see all fields as per usual.

Actual: 
When the name is too long, the id number of the student cannot be seen, which may cause troubles for the tutor managing the students.

![Screenshot 2024-04-05 at 16.42.50.png](https://raw.githubusercontent.com/shavonneg/ped/main/files/a4963ab3-9619-44e2-9679-b564627e9138.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: shavonneg/ped#5

**Comment by MarcusGitty** [comment]
![telegram-cloud-photo-size-5-6091148226238463090-y](https://github.com/AY2324S2-CS2103T-F10-2/tp/assets/122339963/ff2d7311-8a06-4428-a0d0-d8a4ae692eb7)

Lack of it is not a bug - From the TA

**Comment by MarcusGitty** [comment]
https://github.com/nus-cs2103-AY2324S2/forum/issues/700
