### ISSUE TITLE
[PE-D][Tester C] If a special character is added to ID in addressbook.json, view command for all contacts do not work

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-F10-2/tp#151]
Steps to reproduce with an empty addressbook:
- input the following command twice: add -name Xiao Ming -address 13, Computing Dr, 117417 -email xiaoming@email.com -phone 88888888 -subject Math 
- close the application
- open data/addressbook.json
- change the uniqueId to *000001
- open the application
- input the command: view -id 2

Command does not display the student with id 2.

![Screenshot 2024-04-05 at 4.47.11 PM.png](https://raw.githubusercontent.com/martinng01/ped/main/files/d79e55a8-f145-4288-9808-a396f27cfbf1.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: martinng01/ped#6

**Comment by MarcusGitty** [comment]
Changing the database shouldn't be done. can't be fixed

**Comment by MarcusGitty** [comment]
<img width="821" alt="image" src="https://github.com/AY2324S2-CS2103T-F10-2/tp/assets/122339963/5ed4c80b-6d61-4992-886b-f98ed20f4dc3">


Can't fix, need to edit UG

**Comment by MarcusGitty** [comment]
https://github.com/nus-cs2103-AY2324S2/forum/issues/811#issuecomment-2053553793

Not allowed to fix as it meets this bar

 'if you edit the file correctly, things will work. But if you edited it wrongly, there's no guarantee that things will work'. So, I assume you already meet this bar?
