### ISSUE TITLE
[PE-D][Tester A] Student's exam is not deleted when student is deleted

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-F10-2/tp#152]
![image.png](https://raw.githubusercontent.com/Tanzhiheng26/ped/main/files/4b09571b-c0a5-4f01-914e-38c2484e5e8b.png)

Alex Yeoh has been deleted but his exam is still being displayed. I think that when a student is deleted, all exams associated with the student should be deleted.

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: Tanzhiheng26/ped#6

**Comment by MarcusGitty** [comment]
Tested that the PR fixes this bug  !!
