### ISSUE TITLE
[PE-D][Tester B] No GUI feedback when date in the past is entered

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-F10-2/tp#162]
![Screenshot 2024-04-05 at 5.03.45 PM.png](https://raw.githubusercontent.com/chaaaaun/ped/main/files/b67e89e2-615a-4b22-8537-fd314a1b9c2c.png)

For the above command, pressing enter does not result in any visible change in the GUI, even though the date is invalid.

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: chaaaaun/ped#11

**Comment by MarcusGitty** [comment]
Duplicate with #157
