### ISSUE TITLE
[PE-D][Tester B] Exams disappear after restarting

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-F10-2/tp#173]
## Steps to reproduce

1. Create an exam for a student

2. Restart the application

3. Exam is still displayed

4. Add a payment for the same student, then restart the application

## Expected result

Exam is still displayed

## Actual result

Exam disappears

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: chaaaaun/ped#18

**Comment by MarcusGitty** [comment]
Good catch, we fixed it on the day off but too late to be released !
