### ISSUE TITLE
[PE-D][Tester A] Inaccuracy in floating point operations

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-F10-2/tp#184]
![image.png](https://raw.githubusercontent.com/Tanzhiheng26/ped/main/files/143007f6-b8e6-408b-a0e9-6f20b86a69d5.png)

1. addpayment -id 3 -payment 0.1
2. addpayment -id 3 -payment 0.2
3. Press F2

0.1 + 0.2 should be equal to 0.3 but this is not the case due to floating point arithmetic. You can refer to this website for more details and possible solutions: https://0.30000000000000004.com/

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: Tanzhiheng26/ped#17

**Comment by MarcusGitty** [comment]
Unintented behavior, should be able to fix

**Comment by MarcusGitty** [comment]
Closed by PR#210
