### ISSUE TITLE
Using phone number as unique ID (Unique ID Starts from 1)

### ISSUE THREAD

**Issue by Windofbitter** [AY2324S2-CS2103T-F10-2/tp#35]
Should we use phone number as unique ID? as each person should have a unique singapore number, and it is 8 digit, which could also be convenient to be used in other commands like DELETE.

**Comment by MarcusGitty** [comment]
Sound good, for v1.2 i feel we can ignore the edge case when a parent have 2 young children, and enrolled both them for tuition.

Perhaps can filter out based on age in future iterations as mentioned by @KinTatHo

**Comment by MarcusGitty** [comment]
Seems like currently we created a counter variable as uniqueID

https://github.com/AY2324S2-CS2103T-F10-2/tp/blob/a742bb2d240bbabd2076369fdbccc554f0bd0939/src/main/java/seedu/address/model/person/Person.java#L24

**Comment by MarcusGitty** [comment]
We need to discuss more on the uniqueID, isit zerobased ? 
One issue we encounter moving from Index to uniqueID is some condition checking (as shown below), 
Index supports both one and zero based counting,

https://github.com/AY2324S2-CS2103T-F10-2/tp/blob/e8cf851cfab497d76c0e1633d1d42d58927dd450/src/main/java/seedu/address/logic/commands/DeleteCommand.java#L49
