### ISSUE TITLE
As a tutor, I can view the summary statistics

### ISSUE THREAD

**Issue by Windofbitter** [AY2324S2-CS2103T-F10-2/tp#4]
...keep track of the total number of students I have.

**Comment by MarcusGitty** [comment]
<img width="746" alt="image" src="https://github.com/AY2324S2-CS2103T-F10-2/tp/assets/122339963/453aa9da-4174-4682-87f2-3eba5cba4bc0">
Currently (MVP) the popout box is this small tiny cutey little thingy.
