### ISSUE TITLE
Changes to Tag 

### ISSUE THREAD

**Issue by MarcusGitty** [AY2324S2-CS2103T-F10-2/tp#79]
![image](https://github.com/AY2324S2-CS2103T-F10-2/tp/assets/122339963/74245017-8714-4cc0-acee-e8a46ee0d04c)

Changes to Tag ( Kin Tat can do this)
Green TAG - all Paid
Red TAG- owes $XXX

Tag can have two stuff now (Learning style extends Tag?? and payment extends Tag????)

**Comment by KinTatHo** [comment]
Tag no need for changes, its fine
